# Generated by Django 3.1.4 on 2020-12-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='question_text',
            new_name='channel_name',
        ),
        migrations.RemoveField(
            model_name='video',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='video',
            name='video_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
