# Generated by Django 3.1.4 on 2020-12-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201223_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_desc',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='channel',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='channel',
            name='facebook',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='channel',
            name='instagram',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='channel',
            name='linkedin',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='channel',
            name='subscriber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channel',
            name='total_video_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channel',
            name='total_view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channel',
            name='twitter',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
