# Generated by Django 3.1.4 on 2020-12-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201223_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='keyword',
            field=models.CharField(default='', max_length=100),
        ),
    ]
