# Generated by Django 3.1.4 on 2020-12-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_video_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='keyword',
            field=models.CharField(default='', max_length=100),
        ),
    ]
