# Generated by Django 3.1.4 on 2020-12-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201223_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='channel',
            name='facebook',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='channel',
            name='instagram',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='channel',
            name='linkedin',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='channel',
            name='subscriber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='total_video_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='total_view_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='twitter',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='Views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='comments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='dislikes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
