# Generated by Django 3.1.4 on 2020-12-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201223_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='channel_desc',
        ),
    ]
