# Generated by Django 3.1.4 on 2020-12-24 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_channel_channel_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='twitter',
        ),
    ]
