# Generated by Django 3.1.4 on 2020-12-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201224_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='chan',
        ),
        migrations.AddField(
            model_name='video',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='subscriber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='total_video_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='total_view_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='channel_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='channel_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='channel_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
