# Generated by Django 3.1.4 on 2021-07-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210711_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='channel',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='published_at',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
