# Generated by Django 3.1.4 on 2021-07-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210715_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
