# Generated by Django 3.1.4 on 2021-07-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210715_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='is_exported',
            field=models.BooleanField(default=False),
        ),
    ]
