# Generated by Django 3.1.4 on 2021-07-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_keyword_is_exported'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='facebook_handle',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='instagram_handle',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='twitter_handle',
            field=models.URLField(blank=True, null=True),
        ),
    ]
